# Dependencies
pygments:         false

# Permalinks
permalink:        pretty

# Settings
destination:      ./_gh_pages
exclude:          ["README.md"]
paginate:         10
encoding:         UTF-8
future:           false
name:             Built With Ember
url:              http://builtwithember.io
